name: Cypress E2E tests

on: [push]

jobs:
  crc-cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to remote GitHub hosted Ubuntu VM
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress main test section
        uses: cypress-io/github-action@v4.2.0
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable (setup in GitHub project secret settings)
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}