name: Upload index.html to S3 bucket

on: [push]

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Upload file to bucket
        uses: actions/checkout@master
    uses: zdurham/s3-upload-github-action@master
    with:
      args: '--acl public-read'
    env:
      FILE: ./lambda.zip
      AWS_REGION: us-east-1
      S3_BUCKET: '${{ secrets.AWS_S3_BUCKET }}'
      S3_KEY: '${{ secrets.S3_KEY }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'